name: revitool
description: A tool to personalize ReviOS to your needs
publish_to: 'none'

# The version number defaults to 1.0.0 for easier development and is incremented by the build flags based on the tag
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: '>=0.18.0 <= 1.0.0'

  # UI
  fluent_ui: ^4.8.7
  system_theme: ^2.3.1
  fluentui_system_icons: ^1.1.239
  window_plus:
    git:
      url: https://github.com/melo936/window_plus
      # url: https://github.com/alexmercerind/window_plus

  # State management
  provider: ^6.1.2

  # Path
  path_provider: ^2.1.3
  path: ^1.8.3

  # Network
  dio: ^5.4.3+1
  
  # Shell
  process_run: ^0.14.2
  
  # Used to get the version of the app
  package_info_plus: any
  
  # Interactivity with Windows
  # win32: ^5.0.9
  win32_registry: 

  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Logging
  mixin_logger: ^0.1.1

  # Command line
  args: ^2.5.0

  # Other
  collection: ^1.18.0
  xml: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - additionals/
    - additionals/msstore/