name: revitool
description: A tool to personalize ReviOS to your needs
publish_to: 'none'

# The version number defaults to 1.0.0 for easier development and is incremented by the build flags based on the tag
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../common
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: '>=0.18.0 <= 1.0.0'

  # UI
  fluent_ui: ^4.9.2
  system_theme: ^3.1.2
  flutter_acrylic: ^1.1.4
  fluentui_system_icons: ^1.1.264
  window_plus:
    git:
      # url: https://github.com/melo936/window_plus
      url: https://github.com/alexmercerind/window_plus

  # State management
  # provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Path
  path_provider: ^2.1.5
  path: ^1.9.0

  # Network
  dio: ^5.4.3+1
  
  # Shell
  process_run: ^1.1.0
  
  # Used to get the version of the app
  package_info_plus: ^8.0.2
  
  # Interactivity with Windows
  win32: ^5.8.0
  win32_registry: 

  # Code generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Logging
  #logger: ^2.4.0

  # Command line
  args: ^2.5.0

  # Other
  collection: ^1.18.0
  xml: any
  ffi: ^2.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - additionals/
    - additionals/msstore/