param(
    [string] $Version = 'local-controller',
    [switch] $SkipValidation,
    [switch] $SkipGuiBuild,
    [switch] $SkipInstaller,
    [switch] $AllowUnsupportedGui,
    [string] $InnoSetupCompiler,
    [switch] $KeepGeneratedDependencyInclude
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$SrcRoot = Join-Path $RepoRoot 'src'
$InstallerPath = Join-Path $RepoRoot 'RevisionTool-Setup.exe'
$CliPath = Join-Path $RepoRoot 'revitool.exe'
$GuiBuildDir = Join-Path $SrcRoot 'build\windows\x64\runner\Release'
$GuiPath = Join-Path $GuiBuildDir 'revitoolw.exe'
$DependencyInclude = Join-Path $RepoRoot 'CodeDependencies.iss'

function Invoke-Step {
    param(
        [string] $Name,
        [string] $Command,
        [string[]] $Arguments,
        [string] $WorkingDirectory
    )

    Write-Host ''
    Write-Host "==> $Name"
    Push-Location $WorkingDirectory
    try {
        & $Command @Arguments
        $exitCode = $LASTEXITCODE
        if ($null -ne $exitCode -and $exitCode -ne 0) {
            throw "$Name failed with exit code $exitCode."
        }
    } finally {
        Pop-Location
    }
}

function Assert-File {
    param([string] $Path)

    if (!(Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "Required file was not produced: $Path"
    }
}

function Assert-Directory {
    param([string] $Path)

    if (!(Test-Path -LiteralPath $Path -PathType Container)) {
        throw "Required directory was not produced: $Path"
    }
}

function Resolve-InnoCompiler {
    if (![string]::IsNullOrWhiteSpace($InnoSetupCompiler)) {
        $resolved = (Resolve-Path $InnoSetupCompiler).Path
        Assert-File $resolved
        return $resolved
    }

    $command = Get-Command 'iscc.exe' -ErrorAction SilentlyContinue
    if ($command -ne $null) {
        return $command.Source
    }

    $candidates = @(
        (Join-Path $env:LOCALAPPDATA 'Programs\Inno Setup 6\ISCC.exe'),
        (Join-Path ${env:ProgramFiles(x86)} 'Inno Setup 6\ISCC.exe'),
        (Join-Path $env:ProgramFiles 'Inno Setup 6\ISCC.exe')
    )

    foreach ($candidate in $candidates) {
        if (Test-Path -LiteralPath $candidate -PathType Leaf) {
            return $candidate
        }
    }

    throw "Inno Setup compiler was not found. Install Inno Setup 6, or pass -InnoSetupCompiler with the full path to ISCC.exe."
}

function Invoke-CompileSvgVectors {
    $svgRoot = Join-Path $SrcRoot 'assets\icon\pane'
    if (!(Test-Path -LiteralPath $svgRoot -PathType Container)) {
        throw "SVG root not found: $svgRoot"
    }

    $svgs = Get-ChildItem -LiteralPath $svgRoot -Filter '*.svg' -Recurse -File
    foreach ($svg in $svgs) {
        $outputPath = "$($svg.FullName).vec"
        Write-Host "Compiling $($svg.FullName) -> $outputPath"
        Invoke-Step -Name "Compile SVG vector $($svg.Name)" -Command 'dart' -Arguments @('run', 'vector_graphics_compiler', '-i', $svg.FullName, '-o', $outputPath) -WorkingDirectory $SrcRoot
    }
}

function New-TemporaryDependencyInclude {
    param([string] $Path)

    $content = @'
; Local fallback generated by scripts\build-local-controller.ps1 when the
; upstream CodeDependencies.iss include is unavailable in this checkout.
[Code]
procedure Dependency_AddVC2015To2022;
begin
end;
'@

    $encoding = New-Object System.Text.UTF8Encoding -ArgumentList $false
    [IO.File]::WriteAllText($Path, $content, $encoding)
}

function Invoke-CliSmoke {
    Write-Host ''
    Write-Host '==> CLI smoke: revitool.exe profile list'
    $output = & $CliPath profile list 2>&1
    $exitCode = $LASTEXITCODE

    if ($exitCode -eq 0) {
        $output | ForEach-Object { Write-Host $_ }
        return
    }

    if ($exitCode -eq 55) {
        Write-Warning 'CLI compiled, but this host is not marked as ReviOS/AME. Full CLI smoke must run inside the staged VM.'
        $output | ForEach-Object { Write-Host $_ }
        return
    }

    $output | ForEach-Object { Write-Host $_ }
    throw "CLI smoke failed with exit code $exitCode."
}

if (!(Test-Path -LiteralPath $SrcRoot -PathType Container)) {
    throw "Revision Tool src directory was not found: $SrcRoot"
}

if (!$SkipValidation) {
    Invoke-Step -Name 'Generate build_runner outputs' -Command 'dart' -Arguments @('run', 'build_runner', 'build') -WorkingDirectory $SrcRoot
    Invoke-Step -Name 'Generate slang translations' -Command 'dart' -Arguments @('run', 'slang') -WorkingDirectory $SrcRoot
    Invoke-Step -Name 'Analyze Flutter project' -Command 'flutter' -Arguments @('analyze') -WorkingDirectory $SrcRoot
    Invoke-Step -Name 'Run Flutter tests' -Command 'flutter' -Arguments @('test') -WorkingDirectory $SrcRoot
}

Invoke-CompileSvgVectors

Invoke-Step -Name 'Compile CLI executable' -Command 'dart' -Arguments @('compile', 'exe', 'lib/main_cli.dart', "-DAPP_VERSION=$Version", '-o', '..\revitool.exe') -WorkingDirectory $SrcRoot

Assert-File $CliPath
Invoke-CliSmoke

if (!$SkipGuiBuild) {
    $guiBuildArgs = @('build', 'windows', '--release', "--dart-define=APP_VERSION=$Version")
    if ($AllowUnsupportedGui) {
        $guiBuildArgs += '--dart-define=ALLOW_UNSUPPORTED_GUI=true'
    }
    Invoke-Step -Name 'Build Windows GUI' -Command 'flutter' -Arguments $guiBuildArgs -WorkingDirectory $SrcRoot

    Assert-File $GuiPath
    Assert-File (Join-Path $GuiBuildDir 'flutter_windows.dll')
    Assert-File (Join-Path $GuiBuildDir 'window_plus_plugin.dll')
    Assert-File (Join-Path $GuiBuildDir 'system_theme_plugin.dll')
    Assert-File (Join-Path $GuiBuildDir 'flutter_acrylic_plugin.dll')
    Assert-Directory (Join-Path $GuiBuildDir 'data')
    Assert-File (Join-Path $RepoRoot 'native_utils\process_checker.dll')
} else {
    Write-Warning 'Skipped Windows GUI build. Installer generation is not available without the GUI build output.'
}

if ($SkipInstaller) {
    Write-Host ''
    Write-Host "Built local controller binaries:"
    if (!$SkipGuiBuild) {
        Write-Host "  GUI: $GuiPath"
    }
    Write-Host "  CLI: $CliPath"
    exit 0
}

if ($SkipGuiBuild) {
    throw 'Installer generation requires the Windows GUI build output. Rerun without -SkipGuiBuild after installing the Visual Studio C++ desktop workload.'
}

$createdDependencyInclude = $false
if (!(Test-Path -LiteralPath $DependencyInclude -PathType Leaf)) {
    New-TemporaryDependencyInclude $DependencyInclude
    $createdDependencyInclude = $true
    Write-Warning 'CodeDependencies.iss was missing; generated a local no-op dependency include for this installer build.'
}

try {
    $compiler = Resolve-InnoCompiler
    Invoke-Step -Name 'Compile Inno Setup installer' -Command $compiler -Arguments @((Join-Path $RepoRoot 'inno-setup.iss')) -WorkingDirectory $RepoRoot
} finally {
    if ($createdDependencyInclude -and !$KeepGeneratedDependencyInclude) {
        Remove-Item -LiteralPath $DependencyInclude -Force
    }
}

Assert-File $InstallerPath
$hash = Get-FileHash -Algorithm SHA256 -LiteralPath $InstallerPath

Write-Host ''
Write-Host 'Local Revision Tool artifact ready:'
Write-Host "  Installer: $InstallerPath"
Write-Host "  SHA256:    $($hash.Hash)"
