name: revitool
description: A tool to personalize ReviOS to your needs
publish_to: "none"

# The version number defaults to 1.0.0 for easier development and is incremented by the build flags based on the tag
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  # Localization
  slang: ^4.19.0
  slang_flutter: ^4.19.0

  # UI
  fluent_ui: ^4.16.1
  system_theme: ^3.3.0
  flutter_acrylic: ^1.1.4
  fluentui_system_icons: ^1.1.273
  window_plus:
    git:
      # url: https://github.com/melo936/window_plus
      url: https://github.com/alexmercerind/window_plus
  adaptive_palette: ^3.1.0

  # State management
  riverpod: ^3.4.2 # for CLI
  flutter_riverpod: ^3.4.2
  riverpod_annotation: ^4.0.6

  # Path
  path: ^1.9.1

  # Network
  dio: ^5.11.0

  # Shell
  process_run: ^1.3.5

  # Interactivity with Windows
  win32: ^6.4.0
  win32_registry: ^3.0.3

  # Code generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0

  # Logging
  logger: ^2.7.0
  # Command line
  args: ^2.7.0

  # Routing
  go_router: ^18.0.0

  # Other
  collection: ^1.19.1
  xml: ^7.0.1
  ffi: ^2.2.0
  crypto: ^3.0.7
  flutter_svg: ^2.3.0

  # Code generation dependencies
  analyzer: ^13.3.0
  build: ^4.0.10
  code_builder: ^4.11.1
  source_gen: ^4.2.4

  vector_graphics: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.1.8
  build_runner: ^2.16.0
  freezed: ^4.0.0
  json_serializable: ^6.14.1
  riverpod_generator: ^4.0.8
  mocktail: ^1.0.5
  slang_build_runner: ^4.19.0

  

# dependency_overrides:
#   petitparser: ^7.0.2
#   math_expressions: ^3.1.0
  
flutter:
  uses-material-design: false

  assets:
    - assets/
    - assets/icon/
    - assets/icon/pane/
    - additionals/
    - additionals/packages/winsxs/
    - additionals/packages/appx/
